name: Gerar APK Oficial PWABuilder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Gerar Android APK
        uses: pwa-builder/pwa-action@v1
        with:
          url: https://rafael-to-do.glide.page
          platform: android
          
      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-rafael-final
          # O ajuste de "segurança": procura em qualquer subdiretório por arquivos .apk
          path: ./**/*.apk
          # Garante que o build não falhe se o arquivo não for encontrado (ajuda no debug)
          if-no-files-found: error
